export const VALIDATORS_EMAIL_MAX_LENGTH = 75;
export const VALIDATORS_PASSWORD_MAX_LENGTH = 50;

export const VALIDATORS_NAME_MAX_LENGTH = 30;
export const VALIDATORS_SURNAME_MAX_LENGTH = 30;
export const VALIDATORS_PHONE_MAX_LENGTH = 15;
export const VALIDATORS_COUNTRY_MAX_LENGTH = 10;
export const VALIDATORS_REGION_MAX_LENGTH = 10;

export const VALIDATORS_PAYMENT_TYPE_MAX_LENGTH = 10;
export const VALIDATORS_PAYMENT_PROVIDER_MAX_LENGTH = 10;
export const VALIDATORS_ACCOUNT_NO_MAX_LENGTH = 20;
export const VALIDATORS_EXPIRY_MAX_LENGTH = 10;